[programs.devnet]
myepicproject = "AtJZqAe4a2uEJpMtMGHmnuHepz4okdNbQYstodxzPrB9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/kriptikz/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
